---
apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: codimd-deployment 
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector: 
    matchLabels: 
      web: codimd
  replicas: 2 # tells deployment to run 2 pods matching the template 
  template: 
    metadata: 
      labels: 
        web: codimd 
    spec: 
      containers: 
      - name: codimd 
        image: glgelopfalcon/hackmd:v1.1
        ports: 
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 3  
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1      
--- 